// Code generated by qtc from "footer.html.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/footer.html.qtpl:1
package templates

//line templates/footer.html.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/footer.html.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/footer.html.qtpl:1
func StreamFooter(qw422016 *qt422016.Writer, c Postblog) {
//line templates/footer.html.qtpl:1
	qw422016.N().S(`
<footer class="footer has-background-dark">
    <div class="content has-text-centered">
        <p class="has-text-grey-lighter">`)
//line templates/footer.html.qtpl:4
	qw422016.E().S(c.Site.Author)
//line templates/footer.html.qtpl:4
	qw422016.N().S(` &copy; `)
//line templates/footer.html.qtpl:4
	qw422016.E().V(c.BuildTime.Year())
//line templates/footer.html.qtpl:4
	qw422016.N().S(`</p>
        <p>created with <a class="has-text-grey-dark" href="https://github.com/machineandme/postblog">postblog</a></p>
    </div>
</footer>
`)
//line templates/footer.html.qtpl:8
}

//line templates/footer.html.qtpl:8
func WriteFooter(qq422016 qtio422016.Writer, c Postblog) {
//line templates/footer.html.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/footer.html.qtpl:8
	StreamFooter(qw422016, c)
//line templates/footer.html.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line templates/footer.html.qtpl:8
}

//line templates/footer.html.qtpl:8
func Footer(c Postblog) string {
//line templates/footer.html.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/footer.html.qtpl:8
	WriteFooter(qb422016, c)
//line templates/footer.html.qtpl:8
	qs422016 := string(qb422016.B)
//line templates/footer.html.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/footer.html.qtpl:8
	return qs422016
//line templates/footer.html.qtpl:8
}
