// Code generated by qtc from "head.html.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/head.html.qtpl:1
package templates

//line templates/head.html.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/head.html.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/head.html.qtpl:1
func StreamHead(qw422016 *qt422016.Writer, base string, c Postblog, p Page) {
//line templates/head.html.qtpl:1
	qw422016.N().S(`
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="`)
//line templates/head.html.qtpl:5
	qw422016.E().S(c.Site.Author)
//line templates/head.html.qtpl:5
	qw422016.N().S(`">
<meta name="document-state" content="Dynamic">
<meta name="robots" content="index,follow">
<meta name="robots" content="all">
<meta name="theme-color" content="`)
//line templates/head.html.qtpl:9
	qw422016.E().S(c.Theme.Primary)
//line templates/head.html.qtpl:9
	qw422016.N().S(`">
<link rel="icon" type="image/png" href="`)
//line templates/head.html.qtpl:10
	qw422016.E().S(base)
//line templates/head.html.qtpl:10
	qw422016.N().S(`assets/`)
//line templates/head.html.qtpl:10
	qw422016.E().S(c.Asset.Favicon)
//line templates/head.html.qtpl:10
	qw422016.N().S(`" />
<link rel="manifest" href="`)
//line templates/head.html.qtpl:11
	qw422016.E().S(base)
//line templates/head.html.qtpl:11
	qw422016.N().S(`assets/manifest.json">
<title>`)
//line templates/head.html.qtpl:12
	qw422016.E().S(p.Name)
//line templates/head.html.qtpl:12
	qw422016.N().S(` | `)
//line templates/head.html.qtpl:12
	qw422016.E().S(c.Site.Name)
//line templates/head.html.qtpl:12
	qw422016.N().S(`</title>
<meta name="description" content="`)
//line templates/head.html.qtpl:13
	qw422016.E().S(c.Site.Description)
//line templates/head.html.qtpl:13
	qw422016.N().S(`">
<meta itemprop="name" content="`)
//line templates/head.html.qtpl:14
	qw422016.E().S(c.Site.Name)
//line templates/head.html.qtpl:14
	qw422016.N().S(`">
<meta itemprop="description" content="`)
//line templates/head.html.qtpl:15
	qw422016.E().S(c.Site.Description)
//line templates/head.html.qtpl:15
	qw422016.N().S(`">
<meta itemprop="image" content="`)
//line templates/head.html.qtpl:16
	qw422016.E().S(c.Site.Link)
//line templates/head.html.qtpl:16
	qw422016.N().S(`/assets/`)
//line templates/head.html.qtpl:16
	qw422016.E().S(c.Asset.Cover)
//line templates/head.html.qtpl:16
	qw422016.N().S(`">
<meta property="og:url" content="`)
//line templates/head.html.qtpl:17
	qw422016.E().S(c.Site.Link)
//line templates/head.html.qtpl:17
	qw422016.N().S(`">
<meta property="og:type" content="website">
<meta property="og:title" content="`)
//line templates/head.html.qtpl:19
	qw422016.E().S(p.Name)
//line templates/head.html.qtpl:19
	qw422016.N().S(` | `)
//line templates/head.html.qtpl:19
	qw422016.E().S(c.Site.Name)
//line templates/head.html.qtpl:19
	qw422016.N().S(`">
<meta property="og:site_name" content="`)
//line templates/head.html.qtpl:20
	qw422016.E().S(c.Site.Name)
//line templates/head.html.qtpl:20
	qw422016.N().S(`">
<meta property="og:description" content="`)
//line templates/head.html.qtpl:21
	qw422016.E().S(c.Site.Description)
//line templates/head.html.qtpl:21
	qw422016.N().S(`">
<meta property="og:image" content="`)
//line templates/head.html.qtpl:22
	qw422016.E().S(c.Site.Link)
//line templates/head.html.qtpl:22
	qw422016.N().S(`/assets/`)
//line templates/head.html.qtpl:22
	qw422016.E().S(c.Asset.Cover)
//line templates/head.html.qtpl:22
	qw422016.N().S(`">
<meta name="twitter:url" content="`)
//line templates/head.html.qtpl:23
	qw422016.E().S(c.Site.Link)
//line templates/head.html.qtpl:23
	qw422016.N().S(`">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="`)
//line templates/head.html.qtpl:25
	qw422016.E().S(p.Name)
//line templates/head.html.qtpl:25
	qw422016.N().S(` | `)
//line templates/head.html.qtpl:25
	qw422016.E().S(c.Site.Name)
//line templates/head.html.qtpl:25
	qw422016.N().S(`">
<meta name="twitter:site" content="`)
//line templates/head.html.qtpl:26
	qw422016.E().S(c.Site.Name)
//line templates/head.html.qtpl:26
	qw422016.N().S(`">
<meta name="twitter:description" content="`)
//line templates/head.html.qtpl:27
	qw422016.E().S(c.Site.Description)
//line templates/head.html.qtpl:27
	qw422016.N().S(`">
<meta property="twitter:image" content="`)
//line templates/head.html.qtpl:28
	qw422016.E().S(c.Site.Link)
//line templates/head.html.qtpl:28
	qw422016.N().S(`/assets/`)
//line templates/head.html.qtpl:28
	qw422016.E().S(c.Asset.Cover)
//line templates/head.html.qtpl:28
	qw422016.N().S(`">
<link rel="stylesheet" href="`)
//line templates/head.html.qtpl:29
	qw422016.E().S(base)
//line templates/head.html.qtpl:29
	qw422016.N().S(`assets/style.css">
<link rel="stylesheet" href="`)
//line templates/head.html.qtpl:30
	qw422016.E().S(base)
//line templates/head.html.qtpl:30
	qw422016.N().S(`assets/style_font.css">
<link rel="alternate" type="application/rss+xml" title="`)
//line templates/head.html.qtpl:31
	qw422016.E().S(c.Site.Name)
//line templates/head.html.qtpl:31
	qw422016.N().S(`" href="`)
//line templates/head.html.qtpl:31
	qw422016.E().S(c.Site.Link)
//line templates/head.html.qtpl:31
	qw422016.N().S(`/feed.xml">
<link rel="canonical" href="`)
//line templates/head.html.qtpl:32
	qw422016.E().S(c.Site.Link)
//line templates/head.html.qtpl:32
	qw422016.N().S(`">
`)
//line templates/head.html.qtpl:33
}

//line templates/head.html.qtpl:33
func WriteHead(qq422016 qtio422016.Writer, base string, c Postblog, p Page) {
//line templates/head.html.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/head.html.qtpl:33
	StreamHead(qw422016, base, c, p)
//line templates/head.html.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line templates/head.html.qtpl:33
}

//line templates/head.html.qtpl:33
func Head(base string, c Postblog, p Page) string {
//line templates/head.html.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/head.html.qtpl:33
	WriteHead(qb422016, base, c, p)
//line templates/head.html.qtpl:33
	qs422016 := string(qb422016.B)
//line templates/head.html.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/head.html.qtpl:33
	return qs422016
//line templates/head.html.qtpl:33
}
