// Code generated by qtc from "manifest.json.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/manifest.json.qtpl:1
package templates

//line templates/manifest.json.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/manifest.json.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/manifest.json.qtpl:1
func StreamWebmanifest(qw422016 *qt422016.Writer, c Postblog) {
//line templates/manifest.json.qtpl:1
	qw422016.N().S(`
{
  "name": "`)
//line templates/manifest.json.qtpl:3
	qw422016.E().S(c.Site.Name)
//line templates/manifest.json.qtpl:3
	qw422016.N().S(`",
  "short_name": "`)
//line templates/manifest.json.qtpl:4
	qw422016.E().S(c.Site.Name)
//line templates/manifest.json.qtpl:4
	qw422016.N().S(`",
  "description": "`)
//line templates/manifest.json.qtpl:5
	qw422016.E().S(c.Site.Description)
//line templates/manifest.json.qtpl:5
	qw422016.N().S(`",
  "start_url": "`)
//line templates/manifest.json.qtpl:6
	qw422016.E().S(c.Site.Link)
//line templates/manifest.json.qtpl:6
	qw422016.N().S(`",
  "display": "standalone",
  "background_color": "`)
//line templates/manifest.json.qtpl:8
	qw422016.E().S(c.Theme.Primary)
//line templates/manifest.json.qtpl:8
	qw422016.N().S(`",
  "icons": [{
    "src": "/assets/web_icon48.png",
    "sizes": "48x48",
    "type": "image/png"
  }, {
    "src": "/assets/web_icon72.png",
    "sizes": "72x72",
    "type": "image/png"
  }, {
    "src": "/assets/web_icon96.png",
    "sizes": "96x96",
    "type": "image/png"
  }, {
    "src": "/assets/web_icon144.png",
    "sizes": "144x144",
    "type": "image/png"
  }, {
    "src": "/assets/web_icon168.png",
    "sizes": "168x168",
    "type": "image/png"
  }, {
    "src": "/assets/web_icon192.png",
    "sizes": "192x192",
    "type": "image/png"
  }],
  "related_applications": [{
    "platform": "web"
  }]
}
`)
//line templates/manifest.json.qtpl:38
}

//line templates/manifest.json.qtpl:38
func WriteWebmanifest(qq422016 qtio422016.Writer, c Postblog) {
//line templates/manifest.json.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/manifest.json.qtpl:38
	StreamWebmanifest(qw422016, c)
//line templates/manifest.json.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line templates/manifest.json.qtpl:38
}

//line templates/manifest.json.qtpl:38
func Webmanifest(c Postblog) string {
//line templates/manifest.json.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/manifest.json.qtpl:38
	WriteWebmanifest(qb422016, c)
//line templates/manifest.json.qtpl:38
	qs422016 := string(qb422016.B)
//line templates/manifest.json.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/manifest.json.qtpl:38
	return qs422016
//line templates/manifest.json.qtpl:38
}
