// Code generated by qtc from "rss.xml.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/rss.xml.qtpl:1
package templates

//line templates/rss.xml.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/rss.xml.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/rss.xml.qtpl:1
func StreamRSS(qw422016 *qt422016.Writer, c Postblog) {
//line templates/rss.xml.qtpl:1
	qw422016.N().S(`
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>`)
//line templates/rss.xml.qtpl:4
	qw422016.E().S(c.Site.Name)
//line templates/rss.xml.qtpl:4
	qw422016.N().S(`</title>
    <description>`)
//line templates/rss.xml.qtpl:5
	qw422016.E().S(c.Site.Description)
//line templates/rss.xml.qtpl:5
	qw422016.N().S(`</description>
    <link>`)
//line templates/rss.xml.qtpl:6
	qw422016.E().S(c.Site.Link)
//line templates/rss.xml.qtpl:6
	qw422016.N().S(`</link>
    <atom:link href="`)
//line templates/rss.xml.qtpl:7
	qw422016.E().S(c.Site.Link)
//line templates/rss.xml.qtpl:7
	qw422016.N().S(`/feed.xml" rel="self" type="application/rss+xml"/>
    <pubDate>`)
//line templates/rss.xml.qtpl:8
	qw422016.E().V(c.BuildTime)
//line templates/rss.xml.qtpl:8
	qw422016.N().S(`</pubDate>
    <lastBuildDate>`)
//line templates/rss.xml.qtpl:9
	qw422016.E().V(c.BuildTime)
//line templates/rss.xml.qtpl:9
	qw422016.N().S(`</lastBuildDate>
    <generator>MachineandmePostblog (golang version)</generator>
      <item>
        <title>{{article.title}}</title>
        <description>{{article.text}}</description>
        <pubDate>{{article.publication}}</pubDate>
        <link>{{article.link}}</link>
        <guid isPermaLink="true">{{article.link}}</guid>
        <category>{{category}}</category>
        <category>{{category2}}</category>
      </item>
  </channel>
</rss>
`)
//line templates/rss.xml.qtpl:22
}

//line templates/rss.xml.qtpl:22
func WriteRSS(qq422016 qtio422016.Writer, c Postblog) {
//line templates/rss.xml.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/rss.xml.qtpl:22
	StreamRSS(qw422016, c)
//line templates/rss.xml.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line templates/rss.xml.qtpl:22
}

//line templates/rss.xml.qtpl:22
func RSS(c Postblog) string {
//line templates/rss.xml.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/rss.xml.qtpl:22
	WriteRSS(qb422016, c)
//line templates/rss.xml.qtpl:22
	qs422016 := string(qb422016.B)
//line templates/rss.xml.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/rss.xml.qtpl:22
	return qs422016
//line templates/rss.xml.qtpl:22
}
